services:
  # Servicio: Base de datos PostgreSQL
  db:
    image: postgres:16-alpine
    container_name: biblioteca_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: biblioteca_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432" # 5433 en el host para no chocar con Postgres local
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./servidor/DB/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./servidor/DB/seed.sql:/docker-entrypoint-initdb.d/02_seed.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d biblioteca_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # ── Servicio: Servidor Node.js / Express ─────────────────────────────────────
  app:
    build:
      context: . # raíz del proyecto
      dockerfile: servidor/Dockerfile
    container_name: biblioteca_app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db # nombre del servicio en la red Docker
      DB_PORT: 5432
      DB_NAME: biblioteca_db
      DB_USER: postgres
      DB_PASSWORD: ${DB_PASSWORD}

volumes:
  postgres_data:
